name: build and push image 

on:
  push:
    branches: [ "*" ]

permissions:
  contents: write

env:
  IMAGE_NAME: yonatanbesser/yotla-frontend

jobs:
  tag-version:
    uses: yotla/shared-workflows/.github/workflows/tag-version.yaml@0.0.1
    secrets: inherit

  build-and-push-image:
    needs: 
      - tag-version
    runs-on: ubuntu-latest
    steps:
    # steps to support multi-architecture builds
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # checkout source
    - uses: actions/checkout@v4
    # login to dockerhub
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    # build and push image
    - uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        tags: ${{ env.IMAGE_NAME }}:${{ needs.tag-version.outputs.NEW_VERSION }}
        platforms: linux/amd64,linux/arm64
        push: true
